name: Clang-Tidy Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y clang-tidy

      - name: Run Clang-Tidy with Makefile's logic
        run: make lint
